CREATE TABLE IF NOT EXISTS t_art_objects (
	ID TEXT PRIMARY KEY,
	TITLE TEXT,
	DESCRIPTION TEXT,
	PAINTER_ID TEXT
);

CREATE TABLE IF NOT EXISTS t_art_owners (
	ID TEXT PRIMARY KEY,
	OWNER_ID TEXT,
	OWNER_NAME TEXT,
	START_OWNERSHIP TEXT,
	END_OWNERSHIP TEXT
);
