CREATE TABLE t_art_objects (
	ID TEXT PRIMARY KEY,
	DESCRIPTION TEXT,
	PAINTER_ID TEXT,
	CREATION_YEAR YEAR
);

CREATE TABLE t_art_owners (
	ID TEXT PRIMARY KEY,
	OWNER_ID TEXT,
	START_OWNERSHIP YEAR,
	END_OWNERSHIP YEAR
);
